### ISSUE TITLE
运行demo，视频通话没有展现出来，黑屏，但是有声音

### ISSUE THREAD

**Issue by jiasongs** [jpush/jmrtc-react-native#2]

**Comment by huangminlinux** [comment]
在 iOS端 还是 android 端出现的问题？

**Comment by huangminlinux** [comment]
发起通话请求只能显示自己的摄像头影像，要显示接收方的摄像头影像需要接收方接受通话请求才会显示。

**Comment by jiasongs** [comment]
嗯嗯，好的，我再调试一下

**Comment by jiasongs** [comment]
JMRTCViewController.setVideoView({ username: "0001" });
 JMRTCViewController.setVideoView({ username: "0002" });

**Comment by jiasongs** [comment]
我注册了用户qiushui和jiasong，我用jiasong用户call qiushui用户，一直返回code：898002，用户不存在。

**Comment by jiasongs** [comment]
我在开放平台注册了一个用户xifeng，然后我再开放平台点击登录，返回错误码801003，用户未注册。但是我点击注册返回错误码898001，用户已存在。这是什么情况。。。

**Comment by HuminiOS** [comment]
username 要替换成 自己的 targetUsername
JMRTCViewController.setVideoView({ username: "0001" });

**Comment by HuminiOS** [comment]
> 我在开放平台注册了一个用户xifeng，然后我再开放平台点击登录，返回错误码801003，用户未注册。但是我点击注册返回错误码898001，用户已存在。这是什么情况。。。

开放平台具体指的是什么？

**Comment by jiasongs** [comment]
> > 我在开放平台注册了一个用户xifeng，然后我再开放平台点击登录，返回错误码801003，用户未注册。但是我点击注册返回错误码898001，用户已存在。这是什么情况。。。
> 
> 开放平台具体指的是什么？

 不好意思，打错字了。是这样的，我在极光IM应用管理注册了一个用户xifeng，然后在app的demo中点击登录，返回错误码801003，用户未注册。但是我点击注册返回错误码898001，用户已存在。

**Comment by HuminiOS** [comment]
你的意思是在 极光开发者服务->IM->用户管理 中添加的用户无法在 demo 中登录？
jmessage-react-native 用的是什么版本？

**Comment by jiasongs** [comment]
> 你的意思是在 极光开发者服务->IM->用户管理 中添加的用户无法在 demo 中登录？
> jmessage-react-native 用的是什么版本？

是的，jmessage-react-native：2.3.9

**Comment by HuminiOS** [comment]
使用 2.4.5 测试没有这个问题，可以升级看看。

**Comment by jiasongs** [comment]
安卓端。Native component for "RTCJMRTCView" does not exist。我看源码中安卓确实已经导入了，不知demo中为何会出现这个问题

**Comment by JoshLipan** [comment]
添加[JMRTCReactPackage](https://github.com/jpush/jmrtc-react-native/blob/master/example/android/app/src/main/java/com/example/MainApplication.java#L31)了没

**Comment by jiasongs** [comment]
安卓，setVideoView没有实现

**Comment by JoshLipan** [comment]
更新[v1.2.0](https://github.com/jpush/jmrtc-react-native/releases/tag/v1.2.0),统一了两个平台调用方式
