### ISSUE TITLE
集成时出现  Undefined symbol: _OBJC_CLASS_$_JMRTCClient

### ISSUE THREAD

**Issue by hiscc** [jpush/jmrtc-react-native#9]
##  环境
````
"react": "16.8.3",
"react-native": "0.59.0",
"jcore-react-native": "^1.3.5",
"jmessage-react-plugin": "^3.1.7",
"jmrtc-react-native": "^1.0.1",
````
## 错误截图
![image](https://user-images.githubusercontent.com/17979372/64946272-0b29c100-d8a5-11e9-8dfb-3151e8a7284a.png)

**Comment by hiscc** [comment]
> ## 环境
> ```
> "react": "16.8.3",
> "react-native": "0.59.0",
> "jcore-react-native": "^1.3.5",
> "jmessage-react-plugin": "^3.1.7",
> "jmrtc-react-native": "^1.0.1",
> ```
> 
> ## 错误截图
> ![image](https://user-images.githubusercontent.com/17979372/64946272-0b29c100-d8a5-11e9-8dfb-3151e8a7284a.png)

时隔多月我终于解决了这个问题。主要还是 iOS 这边的构建导入产生的问题。在 Libraries 下重新手动引入下图的这三个包，重新构建运行即可

<img width="275" alt="引入包2" src="https://user-images.githubusercontent.com/17979372/71392627-b2a45580-2643-11ea-81b7-6e24f50c3101.png">

在 node_modules 下找到这三个文件添加即可

<img width="803" alt="2" src="https://user-images.githubusercontent.com/17979372/71393965-17fb4500-264a-11ea-848e-08b3b66b51be.png">

**Comment by esdotzed** [comment]
@hiscc 我遇到了不一样的问题是ld: library not found for -lRCTJMRTCModule，但是好像和你这个有点像，用了你的这个方法没有效果，请问有什么解决思路吗？

**Comment by esdotzed** [comment]
我按照楼主的思路照样做了没用，于是我在楼主的基础上又进行了如下操作：
我在build phases - Dependencies 里面加入了RCTJMRTCModule，然后我又在Build settings里面的framework search path 加入了$(SRCROOT)/../node_modules/jmrtc-react-native/ios/RCTJMRTCModule
现在我可以编译成功了。希望对后来的人有帮助。

**Comment by hiscc** [comment]
> 我按照楼主的思路照样做了没用，于是我在楼主的基础上又进行了如下操作：
> 我在build phases - Dependencies 里面加入了RCTJMRTCModule，然后我又在Build settings里面的framework search path 加入了$(SRCROOT)/../node_modules/jmrtc-react-native/ios/RCTJMRTCModule
> 现在我可以编译成功了。希望对后来的人有帮助。
